services:
  kg_boilers_postgres:
    image: postgres:16.2
    container_name: kg_boilers_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5435}:5432"
    volumes:
      - kg_boilers_pgdata:/var/lib/postgresql/data

volumes:
  kg_boilers_pgdata: